[package]
name = "forge"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive", "cargo"] }
indoc = "2.0.5"
lazy_static = "1.5.0"
sorted-vec = "0.8.3"
termcolor = "1.4.1"
thiserror = "1.0.62"
inkwell = { version = "0.5.0", features = ["llvm17-0"] }
