[package]
name = "forge-compiler"
description = "The Forge compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
forge-parsing = { path = "../forge-parsing" }
forge-reporting = { path = "../forge-reporting" }
