[package]
name = "forge-parsing"
description = "A language-agnostic parsing crate using recursive descent"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.63"
unicode-ident = "1.0.13"
unicode-segmentation = "1.12.0"
