name: Build and Test C Project

runs: 
  using: composite
  steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build Core
      working-directory: forge-core
      shell: bash
      run: |
        meson setup build
        meson compile -C build

    - name: Run tests
      working-directory: forge-core
      shell: bash
      run: |
        meson test -C build
