name: Build and Test C Project

runs: 
  using: composite
  steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Python environment
      shell: bash
      run: |
        python3.11 -m venv .venv
        . .venv/bin/activate
        pip3.11 install meson

    - name: Build Core
      working-directory: forge-core
      shell: bash
      run: |
        . ../.venv/bin/activate
        git config --global --add safe.directory $(realpath ..)
        meson setup build -Dtest_mode=full
        meson compile -C build

    - name: Run tests
      working-directory: forge-core
      shell: bash
      run: |
        . ../.venv/bin/activate 
        meson test -v -C build
