# Copyright (c) 2024 Sophie Katz
#
# This file is part of Forge.
#
# Forge is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation, either
# version 3 of the License, or (at your option) any later version.
#
# Forge is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with Forge. If
# not, see <https://www.gnu.org/licenses/>.

name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'forge-core/**'
  workflow_dispatch:

jobs:
  ci_docker:
    name: CI (Docker image)
    runs-on: ubuntu-latest
    container:
      image: sophiekatz/forge-development:latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Run CI
        uses: ./.github/actions/ci

  ci_ubuntu:
    name: CI (Ubuntu Jammy)
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update -y && \
          apt-get upgrade -y && \
          apt-get install -y \
              bison \
              cmake \
              flex \
              git \
              gnupg \
              libglib2.0-0 \
              libglib2.0-dev \
              lsb-release \
              ninja-build \
              python3-pip \
              python3.11 \
              python3.11-venv \
              software-properties-common \
              wget \
          ;
      
      - name: Install LLVM and Clang
        run: |
          echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main" > /etc/apt/sources.list.d/apt.llvm.org.list && \
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc && \
          apt-get update -y && \
          apt-get install -y \
              clang-17 \
              clang-format-17 \
              clang-tidy-17 \
              clang-tools-17 \
              clangd-17 \
              libc++-17-dev \
              libc++abi-17-dev \
              libclang-17-dev \
              libclang-common-17-dev \
              libclang-cpp17-dev \
              libclang-rt-17-dev \
              libomp-17-dev \
              libpolly-17-dev \
              libunwind-17-dev \
              lld-17 \
              lldb-17 \
              llvm-17-dev \
              llvm-17-tools \
          ;

      - name: Update alternatives
        run: |
          update-alternatives --install /usr/bin/clang clang /usr/bin/clang-17 100 && \
          update-alternatives --install /usr/bin/cc cc /usr/bin/clang-17 100 && \
          update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-17 100 && \
          update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-17 100 && \
          update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-17 100 && \
          update-alternatives --install /usr/bin/lldb lldb /usr/bin/lldb-17 100 && \
          update-alternatives --install /usr/bin/lld lld /usr/bin/lld-17 100 && \
          update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-17 100

      - name: Run CI
        uses: ./.github/actions/ci

  ci_debian:
    name: CI (Debian Bookworm)
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update -y && \
          apt-get upgrade -y && \
          apt-get install -y \
              bison \
              cmake \
              flex \
              git \
              gnupg \
              libglib2.0-0 \
              libglib2.0-dev \
              lsb-release \
              ninja-build \
              python3-pip \
              python3.11 \
              python3.11-venv \
              software-properties-common \
              wget \
          ;
      
      - name: Install LLVM and Clang
        run: |
          echo "deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-17 main" > /etc/apt/sources.list.d/apt.llvm.org.list && \
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc && \
          apt-get update -y && \
          apt-get install -y \
              clang-17 \
              clang-format-17 \
              clang-tidy-17 \
              clang-tools-17 \
              clangd-17 \
              libc++-17-dev \
              libc++abi-17-dev \
              libclang-17-dev \
              libclang-common-17-dev \
              libclang-cpp17-dev \
              libclang-rt-17-dev \
              libomp-17-dev \
              libpolly-17-dev \
              libunwind-17-dev \
              lld-17 \
              lldb-17 \
              llvm-17-dev \
              llvm-17-tools \
          ;

      - name: Update alternatives
        run: |
          update-alternatives --install /usr/bin/clang clang /usr/bin/clang-17 100 && \
          update-alternatives --install /usr/bin/cc cc /usr/bin/clang-17 100 && \
          update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-17 100 && \
          update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-17 100 && \
          update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-17 100 && \
          update-alternatives --install /usr/bin/lldb lldb /usr/bin/lldb-17 100 && \
          update-alternatives --install /usr/bin/lld lld /usr/bin/lld-17 100 && \
          update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-17 100

      - name: Run CI
        uses: ./.github/actions/ci
  