# Copyright (c) 2023 Sophie Katz
#
# This file is part of Forge.
#
# Forge is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation, either
# version 3 of the License, or (at your option) any later version.
#
# Forge is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with Forge. If
# not, see <https://www.gnu.org/licenses/>.

name: Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-documentation:
    name: Publish user documentation
    runs-on: ubuntu-latest
    steps:
      - name: Install Doxygen
        run: |
          sudo apt-get update -y
          sudo apt-get install -y doxygen

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
      
      - name: Deploy documentation
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: main/docs/for-users/mkdocs.yml
      
      - name: Build documentation
        working-directory: main/forge-compiler
        run: |
          mkdir -p build/doxygen
          doxygen

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Deploy documentation
        run: |
          rm -rf gh-pages/compiler-api
          mkdir -p gh-pages/compiler-api
          cp -rvf main/forge-compiler/build/doxygen/html/* gh-pages/compiler-api
          cd gh-pages
          git config user.name "Sophie Katz"
          git config user.email "sophie@sophiekatz.us"
          git add -A .
          git commit -am "Update Forge compiler Doxygen documentation"
          git push
